### ISSUE TITLE
Geta.Mapping

### ISSUE THREAD

**Issue by lars-w-pedersen** [Geta/geta-optimizely-sitemaps#24]
Geta.Optimizely.Sitemaps depends on Geta.Mapping but that nuget package does not exist, so i get this error when installing Geta.Optimizely.Sitemaps 1.0.0-rc:

Unable to find package Geta.Mapping. No packages exist with this id in source(s): episerver, episerver-beta, nuget.org

**Comment by brianweet** [comment]
On its way to the opti nuget feed

**Comment by marisks** [comment]
Already on Nuget.org
