### ISSUE TITLE
Unable to find a module by assembly Geta.Optimizely.Sitemaps

### ISSUE THREAD

**Issue by jarihaa** [Geta/geta-optimizely-sitemaps#26]
- Setup Foundation site
- Install Geta.Optimizely.Sitemaps 1.0.0-rc4 package
- Build, start and go to edit

There is a following error,

An unhandled exception occurred while processing the request.

ArgumentException: Unable to find a module by assembly 'Geta.Optimizely.Sitemaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (Parameter 'moduleAssembly')

EPiServer.Shell.Paths.ToResource(Assembly moduleAssembly, string moduleRelativeResourcePath)

**Comment by verbeeksteven** [comment]
Also getting this same error.

**Comment by tednyberg** [comment]
For me this happened before I invoked `services.AddSitemaps(x => {}` in `ConfigureServices`.

However, after adding it, I get a 404 for `/Geta.Optimizely.Sitemaps` when clicking **Seo sitemaps** in the main nav bar.

**Comment by marisks** [comment]
@tednyberg Do you have Razor pages configured?

**Comment by brianweet** [comment]
This error can occur if you don't call the `AddSitemaps` extension method (thanks @tednyberg).
@jarihaa could that be the case here? Or could you try again using a non `rc` version?

@tednyberg As Maris mentioned, if you get a 404 on the sitemaps tab be sure to call `MapRazorPages` during startup, like so:

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
});
```

**Comment by jarihaa** [comment]
I was able to fix this by switching to non rc version.
