### ISSUE TITLE
404 on generated sitemaps

### ISSUE THREAD

**Issue by QuirijnLangedijk** [Geta/geta-optimizely-sitemaps#28]
By using the workaround mentioned in #27 im able to generate sitemaps:
![image](https://user-images.githubusercontent.com/31623496/144068902-963b109e-7d02-4cdd-8bef-f5bba5f67d73.png)

However, this link gives a 404 when visited:
![image](https://user-images.githubusercontent.com/31623496/144068992-9bb0e57b-7478-4157-8452-387b0362d06f.png)

This also happens when creating sitemaps with a wildcard language.
Any fix for this?

**Comment by brianweet** [comment]
Fixed in #36
