### ISSUE TITLE
Sitemap data not found

### ISSUE THREAD

**Issue by verbeeksteven** [Geta/geta-optimizely-sitemaps#37]
Hello,

I am using `1.0.1` and no matter what I try I cannot get this to work.

In my job I see

```
Job successfully executed.
Generated sitemaps:
"http://localhost:8000/sitemap.xml": 12 entries
```

If I go to `http://localhost:8000/sitemap.xml` I get a 404

```
Geta.Optimizely.Sitemaps.Controllers.GetaSitemapController[0]
Xml sitemap data not found!
```

I have two languages, EN and FR (both /en/ and /fr/ added to the URL does nothing), using the latest OptimizelyCMS.

I have

```
services.AddSitemaps(x =>
{
    x.EnableLanguageDropDownInAdmin = false;
    x.EnableRealtimeCaching = true;
    x.EnableRealtimeSitemap = false;
});
```

And I have the `MapRazorPages()`.

Everything seems to work but it just won't return the sitemap data.

**Comment by brianweet** [comment]
Did this happen after an upgrade or did you just start using the package?
What do you see when go to `http://localhost:8000/sitemapindex.xml`?

**Comment by brianweet** [comment]
What response do you get if you visit the index: `http://localhost:8000/sitemapindex.xml`?
Can you post a screenshot of your configuration?

**Comment by vicr123** [comment]
We're running into this issue as well, and it seems to be because only the host is being passed to the `ISiteDefinitionResolver`; it neglects the port.

https://github.com/Geta/geta-optimizely-sitemaps/blob/5bfa8a265e8efb937df1ae869d01104a52ec7c03/src/Geta.Optimizely.Sitemaps/Repositories/SitemapRepository.cs#L49
