### ISSUE TITLE
Extend Admin GUI tool with regards to implementation & User friendliness to exclude certain fields from the final sitemap.xml file

### ISSUE THREAD

**Issue by ShaikhFarhin** [Geta/geta-optimizely-sitemaps#46]
1- **Out of the box/Custom implementation for getting the filtered dropdown list of sites:**
     Including the package in my multi site application ,the dropdown lists of sites shows both http & https sites. Can there be a custom implementation to overwrite **GetSiteHosts** and **ShouldAddToSiteHosts** methods that will filter out the list to include only https sites.
Another customization that I am looking for is to filter the dropdown list based on a site level property setting to exclude/include the site itself from appearing in the dropdown list.
I believe having a site level configured filtered list will eliminate the chances of editorial mistakes to generate unwanted or unsecured list of sitemap for a site.
2- **Option to exclude Priority & Frequency from the generated XML similar to Debug Info.**
    Google's general guideless for sitemap slates that it ignores priority & frequency & only considers lastmod value(https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#general-guidelines).So just like Debug info option ,can there be a setting to exclude priority/frequency from the xml file?

**Comment by marisks** [comment]
1. Just do not add hosts with HTTP if you do not want HTTP sites.
Another thing is that this is an admin tool. Admins should be quite educated to know what sitemaps are needed and what should be configured. So filtering out sites for admin is not worth the effort to implement such a feature.
2. Please create a separate issue. Don't mix multiple features/issues in one issue, please.

**Comment by marisks** [comment]
2. Also, what issues do you have by having priority and frequency values in the XML?

**Comment by ShaikhFarhin** [comment]
> 1. tool

There's no issue with having them but if it is not being considered by major search engine then it could be eliminated from the xml file.Also ,both of the points mentioned are not issues but more of feature request. May be I missed to add some label around it mentioning it as a feature request.

**Comment by marisks** [comment]
@ShaikhFarhin 
1. Probably you do not have HTTPS configured for hosts. 
![image](https://user-images.githubusercontent.com/646298/165750234-cc4879c7-e5a8-4c7c-b33f-c559483166ab.png)

2. I don't see any benefit of excluding these two fields if Google doesn't mind about them. Also, in their documentation, they say that they "currently" do not use these values. So in the future, they might.  And there are also other search engines and tools that might use those values. If you find anything that these fields break, we could implement it or just remove these fields.

**Comment by ShaikhFarhin** [comment]
> 2\. these

Thank you for pointing out the settings for HTTPS configured hosts which was not set & so the list included both HTTP & HTTPS within the list.
