### ISSUE TITLE
Cloudflare blocks Geta Sitemaps

### ISSUE THREAD

**Issue by Caroline-Prince** [Geta/geta-optimizely-sitemaps#60]
Hi,

I'm using Geta Sitemaps for an Episerver/Optimizely solution in NET5

Cloudflare seems to block us when we tried to see a part of the website using this plug in.

![image](https://user-images.githubusercontent.com/106403078/197615821-b626d80d-8225-4e89-a1d2-5fdb83c01c17.png)

We noticed this issue on october 24, 2:45pm EST. Everything was well few hours before.
Is there something we can do?

Thank you

Caroline

**Comment by 4nderss** [comment]
Same issue for us. 

`/home/vsts/work/1/s/x.csproj : error NU1301: Failed to retrieve information about 'Geta.Optimizely.Sitemaps' from remote source 'https://api.nuget.optimizely.com/v3/package/geta.optimizely.sitemaps/index.json'. 
/home/vsts/work/1/s/x.csproj : error NU1301: Failed to retrieve information about 'Geta.NotFoundHandler.Admin' from remote source 'https://api.nuget.optimizely.com/v3/package/geta.notfoundhandler.admin/index.json'. 
/home/vsts/work/1/s/x.csproj : error NU1301: Failed to retrieve information about 'Geta.NotFoundHandler.Admin' from remote source 'https://api.nuget.optimizely.com/v3/package/geta.notfoundhandler.admin/index.json'.

`

**Comment by mgnusl** [comment]
You need to upgrade to the newest version released today. A critical bug was found in the plugin, so seems like Optimizely has added a global Cloudflare block to all sites running the affected versions in DXP. The same applies to NotFoundHandler

**Comment by valdisiljuconoks** [comment]
Please use v3.0 - https://api.nuget.optimizely.com/packages/geta.optimizely.sitemaps/3.0.0
