### ISSUE TITLE
Latest Sitemaps and NotFoundHandler dont work together in .Net6

### ISSUE THREAD

**Issue by lanorkin** [Geta/geta-optimizely-sitemaps#61]
Related to https://github.com/Geta/geta-optimizely-sitemaps/issues/60 and https://github.com/Geta/geta-notfoundhandler/issues/52

If we try to use Geta.Optimizely.Sitemaps 3.0.0 and Geta.NotFoundHandler 5.0.0 in Net6 - it won't build

To reproduce (assuming Net6 installed):

```
dotnet new web
dotnet add package EPiServer.CMS
dotnet add package Geta.Optimizely.Sitemaps
dotnet add package Geta.NotFoundHandler.Admin
dotnet add package Geta.NotFoundHandler.Optimizely
dotnet build
```

error during build:

```
error : Two assets found targeting the same path with incompatible asset kinds:  [C:\work\temp\geta6\geta6.csproj]
error : '<..>\packages\geta.optimizely.sitemaps\3.0.0\contentFiles\any\net6.0\wwwroot\css\dashboard.css' with kind 'All' [C:\work\temp\geta6\geta6.csproj]
error : '<..>\packages\geta.notfoundhandler.admin\5.0.0\contentFiles\any\net6.0\wwwroot\css\dashboard.css' with kind 'All' [C:\work\temp\geta6\geta6.csproj]
error : for path 'css/dashboard.css' [C:\work\temp\geta6\geta6.csproj]
```

**Comment by marisks** [comment]
@lanorkin How does your `csproj` look like?

**Comment by marisks** [comment]
@lanorkin I could reproduce it. You should not install both - Geta.NotFoundHandler.Admin and Geta.NotFoundHandler.Optimizely. Install just Geta.NotFoundHandler.Optimizely which will include Geta.NotFoundHandler.Admin as a dependency.

I will check how to fix this. But it seems related to this: https://github.com/dotnet/aspnetcore/issues/39606 and it will be fixed only in .NET 7.

**Comment by lanorkin** [comment]
Thanks @marisks by doing this I cannot control specific lib versions; but seems it is working as a work around, so closing it.
